title: Subham Mitra
description: Subham Mitra's personal website
baseurl: /
lowercase: false

# theme: hacked-jekyll
newtab: true

remote_theme: piazzai/hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
